interface YunitUser {
    activeCode: string
    activeStatus: boolean
    activeTime: string
    birthday: string
    businessId: string
    centerBackground: string
    codeTime: string
    createBy: string
    createTime: string
    deleteTime: string
    deleted: number
    dingding: string
    email: string
    gender: number
    github: string
    id: string
    idNo: number
    introduce: string
    jobinfo: string
    md5pwd: string
    mobile: number
    nickname: string
    nicknamePinyin: string
    realname: string
    registerIp: string
    residence: string
    salt: string
    saying: string
    schoolinfo: string
    status: number
    sysOrgCode: string
    updateBy: string
    updateTime: string
    userphoto: string
    wechat: string
    componentTotal: number
    fansTotal: number
    likeTotal:  number
    orgTotal: number
    level: number
    messageCount: number
    businessName: string
    jobInfo: string
}
